Repository Doer-org/TomoShiru, pull requests merged in 2023-05, with the labels that each got.

#17 Feat(button): ボタン追加
  client/src/app/_ui/debug-button/components/debug-button.tsx
  client/src/app/page.tsx
  client/src/ui/button/components/button.css
  client/src/ui/button/components/button.tsx
  client/src/ui/button/stories/button.stories.ts
  client/src/ui/button/stories/button.stories.tsx
  client/src/ui/button/styles/button.css.ts
  client/src/ui/header/components/header.tsx
Labels: 📦 component, 📝 document

#26 Feat(avator): アバターコンポーネント追加
  client/src/ui/avator/components/avator.tsx
  client/src/ui/avator/components/index.ts
  client/src/ui/avator/index.ts
  client/src/ui/avator/stories/avator.stories.tsx
  client/src/ui/avator/styles/avator.css.ts
Labels: 📦 component, 📝 document

#31 Chore(stories): change story meta
  client/src/ui/avator/stories/avator.stories.tsx
  client/src/ui/button/stories/button.stories.tsx
Labels: 📝 document

#29 Feat(card): カードコンポーネント追加
  client/src/ui/card/components/card.tsx
  client/src/ui/card/components/index.ts
  client/src/ui/card/index.ts
  client/src/ui/card/stories/card.stories.tsx
  client/src/ui/card/styles/card.css.ts
Labels: 📦 component, 📝 document

#46 Feat(client): いいねコンポーネントの追加
  client/src/ui/like/components/index.ts
  client/src/ui/like/components/like.tsx
  client/src/ui/like/index.ts
  client/src/ui/like/stories/like.stories.tsx
  client/src/ui/like/styles/like.css.ts
Labels: 📦 component, 📝 document

#37 Feat(client): ハンバーガーメニューを作成
  client/src/ui/hamburger/components/hamburger.tsx
  client/src/ui/hamburger/components/index.ts
  client/src/ui/hamburger/index.ts
  client/src/ui/hamburger/stories/hamburger.stories.tsx
  client/src/ui/hamburger/styles/hamburger.css.ts
Labels: 📦 component, 📝 document

#57 Feat(client): 戻るボタンを追加
  client/src/ui/arrow/components/arrow.tsx
  client/src/ui/arrow/components/index.ts
  client/src/ui/arrow/index.ts
  client/src/ui/arrow/stories/arrow.stories.tsx
  client/src/ui/arrow/styles/arrow.css.ts
  client/src/ui/index.ts
Labels: 📦 component, 📝 document

#54 Feat(client): ヘッダーコンポーネントを追加
  client/src/app/_ui/common-header/components/common-header.tsx
  client/src/app/_ui/common-header/components/index.ts
  client/src/app/_ui/common-header/index.ts
  client/src/app/_ui/common-header/stories/common-header.stories.tsx
  client/src/app/_ui/common-header/styles/common-header.css.ts
  client/src/app/_ui/profile-header/components/index.ts
  client/src/app/_ui/profile-header/components/profile-header.tsx
  client/src/app/_ui/profile-header/index.ts
  client/src/app/_ui/profile-header/stories/profile-header.stories.tsx
  client/src/app/_ui/profile-header/styles/profile-header.css.ts
  client/src/ui/arrow/stories/arrow.stories.tsx
  client/src/ui/button/components/button.tsx
  client/src/ui/button/styles/button.css.ts
  client/src/ui/header/components/header.css
  client/src/ui/header/components/header.tsx
  client/src/ui/header/stories/header.stories.ts
  client/src/ui/header/styles/header.css.ts
  client/src/ui/index.ts
Labels: 📦 component, 📝 document

#64 headerのpaddingを変更
  client/src/ui/header/styles/header.css.ts
Labels: 📦 component
